Bump nodejs dependency on on libuv.
nodejs 0.12.2 requires libuv 1.4.2, otherwise many packages fail
with an error similar to:
net.js:164
        throw errnoException(err, 'setBlocking');
              ^
Error: setBlocking ENOSYS

Fixes bug 545618